name: Deploy

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: (Image) Build & Push
        uses: jerray/publish-docker-action@master
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: docker.pkg.github.com
          repository: ${{ github.actor }}/anecdotes-yandex-alice-skill/yandex-alice-anecdotes
          auto_tag: true

      - name: (Container) Create & Run
        uses: appleboy/ssh-action@master
        continue-on-error: true
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSHKEY }}
          script: |
            echo "${{ secrets.ENV }}" > .env
            docker rm $(docker stop $(docker ps -a -q --filter ancestor=anecdotes-yandex-alice-skill/yandex-alice-anecdotes --format="{{.ID}}"))
            docker pull docker.pkg.github.com/4llower/anecdotes-yandex-alice-skill/yandex-alice-anecdotes
            docker run --mount type=bind,source=/home/credentials/,target=/home/credentials/ -d -p 443:9000 --env-file .env docker.pkg.github.com/4llower/anecdotes-yandex-alice-skill/yandex-alice-anecdotes
