name: Deploy

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Docker Authorize
        env:
          DOCKER_USER: ${{secrets.DOCKER_USER}}
          DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
        run: |
          docker login -u $DOCKER_USER -p $DOCKER_PASSWORD

      - name: Docker Publish
        run: docker push ${{secrets.DOCKER_USER}}/yandex-alice-anecdotes

      - name: Build and Run
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          USERNAME: ${{ secrets.USERNAME }}
          KEY: ${{ secrets.SSHKEY }}
          script: |
            sudo kill -9 `sudo lsof -t -i:9000`
            docker run -p 80:9000 -it ${{secrets.DOCKER_USER}}/yandex-alice-anecdotes
