name: Deploy

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Build and push docker image
        uses: jerray/publish-docker-action@master
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: docker.pkg.github.com
          repository: ${{ github.actor }}/anecdotes-yandex-alice-skill/yandex-alice-anecdotes
          auto_tag: true

      - name: Build and Run
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          USERNAME: ${{ secrets.USERNAME }}
          KEY: ${{ secrets.SSHKEY }}
          script: |
            fuser 9000/tcp
            docker run -p 80:9000 -it docker.pkg.github.com/${{ github.actor }}/anecdotes-yandex-alice-skill/yandex-alice-anecdotes
